// <auto-generated />
using System;
using Dashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dashboard.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActiveHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnomalyFlags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClockIn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClockOut")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConnectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DowntimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstPublicIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FlagCount")
                        .HasColumnType("int");

                    b.Property<int?>("IPChanges")
                        .HasColumnType("int");

                    b.Property<string>("ISP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("InteractiveEvents")
                        .HasColumnType("bigint");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastPublicIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationVerdict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("M365Hours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NewUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfficeBranch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PreviousDayWorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResearchNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WorkHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("WorkHoursChange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("XplanAfterHoursSessions")
                        .HasColumnType("int");

                    b.Property<decimal?>("XplanHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("XplanOvernightSessions")
                        .HasColumnType("int");

                    b.Property<string>("XplanResources")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("XplanSessions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserActivities");
                });
#pragma warning restore 612, 618
        }
    }
}
